# Generated by Django 5.0.7 on 2024-08-06 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_event_guests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='guests',
        ),
    ]
