# Generated by Django 5.0.7 on 2024-08-06 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_event_guests'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('other', 'Other'), ('work', 'Work'), ('sport', 'Sport'), ('birthday', 'Birthday'), ('wedding', 'Wedding'), ('anniversary', 'Anniversary'), ('concert', 'Concert'), ('holiday', 'Holiday')], default='other', max_length=20),
        ),
    ]
