# Generated by Django 5.0.7 on 2024-08-06 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_event_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('Other', 'Other'), ('Work', 'Work'), ('Sport', 'Sport'), ('Birthday', 'Birthday'), ('Wedding', 'Wedding'), ('Anniversary', 'Anniversary'), ('Concert', 'Concert'), ('Holiday', 'Holiday')], default='Other', max_length=20),
        ),
    ]
